const ACHIEVEMENTTYPE = {
  Achievement: "Achievement",
  AssessmentResult: "Assessment Result",
  Award: "Award",
  Badge: "Badge",
  Certification: "Certification",
  Course: "Course",
  CommunityService: "Community Service",
  Competency: "Competency",
  CoCurricular: "Co-Curricular",
  Degree: "Degree",
  Diploma: "Diploma",
  ExamCredit: "ExamCredit",
  Fieldwork: "Fieldwork",
  License: "License",
  Membership: "Membership",
  TransferCredit: "TransferCredit",
  MissingCredit: "MissingCredit",
  TransferDegree: "TransferDegree",
  Honors: "Honors",
  Major: "Major",
  Minor: "Minor",
  ROTC: "ROTC",
  Certificate: "Certificate",
  PreProfessional: "Pre-Professional",
  Concentration: "Concentration",
};

module.exports = ACHIEVEMENTTYPE;
